export const artistImages = {
  "Kendrick Lamar": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1IPOOk-default.jpg",
  "Eminem": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4gTUOY-default.jpg",
  "TOOL": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1sZyol-default.jpg",
  "System Of A Down": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO34PI4g-default.jpg",
  "J. Cole": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3K21mU-default.jpg",
  "Earl Sweatshirt": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO259NXG-default.jpg",
  "BROCKHAMPTON": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0Tiwvu-default.jpg",
  "Vince Staples": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3Cn7Uc-default.jpg",
  "Kanye West": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3nMr04-default.jpg",
  "Slow J": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4g9ryw-default.jpg",
  "Isaiah Rashad": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3DtS8g-default.jpg",
  "ScHoolboy Q": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3mEAzS-default.jpg",
  "Logic": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2F7UBi-default.jpg",
  "Tyler, The Creator": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2T8209-default.jpg",
  "Denzel Curry": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3GI3JK-default.jpg",
  "XXXTENTACION": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0AnZXW-default.jpg",
  "Machine Gun Kelly": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO44TgnC-default.jpg",
  "G-Eazy": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evNZWVtPW-default.jpg",
  "Joey Bada$$": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1CSf4Y-default.jpg",
  "Drake": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2h63Cw-default.jpg",
  "ProfJam": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO274S8E-default.jpg",
  "Rae Sremmurd": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4k5U2c-default.jpg",
  "Nas": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO18oyZi-default.jpg",
  "Childish Gambino": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4aKvZe-default.jpg",
  "A$AP Rocky": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0yVwSk-default.jpg",
  "The Weeknd": "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da843bc8cf556e988a0b45a1a9ac",
  "Papillon": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0oHq5X-default.jpg",
  "SHAHMEN": "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84be266654abc19e9c8f50b1eb",
  "Hopsin": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4xj4Ji-default.jpg",
  "Ski Mask The Slump God": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1oyk9O-default.jpg",
  "Mac Miller": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2NufN6-default.jpg",
  "Jay Rock": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1dlawg-default.jpg",
  "Big Sean": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO02KO6k-default.jpg",
  "Tech N9ne": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO45pZcs-default.jpg",
  "Travis Scott": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0vGf4I-default.jpg",
  "Lund": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3ez1yw-default.jpg",
  "Migos": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3MgT4c-default.jpg",
  "Bas": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO48PrOg-default.jpg",
  "Trippie Redd": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO471fR6-default.jpg",
  "Wet Bed Gang": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO37DuYE-default.jpg",
  "Post Malone": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1aBeik-default.jpg",
  "Yelawolf": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3CyFXy-default.jpg",
  "Russ": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgs_JQJVa2mJZFPn0329wOirWcufNEkf-FKg&s",
  "Nirvana": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3M0Fbi-default.jpg",
  "GROGNation": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0Nmk1j-default.jpg",
  "21 Savage": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO152G0U-default.jpg",
  "Black Pumas": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3GkpwY-default.jpg",
  "Pusha T": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0q5Ls4-default.jpg",
  "Desiigner": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4o6Lio-default.jpg",
  "Lil Wayne": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2ZpGiQ-default.jpg",
  "6LACK": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2LMnXG-default.jpg",
  "Doja Cat": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO33svt5-default.jpg",
  "Saba": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4yJ4nC-default.jpg",
  "YG": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1S4SJy-default.jpg",
  "Montana of 300": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4bcQ1y-default.jpg",
  "The Notorious B.I.G.": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO39qAJG-default.jpg",
  "JID": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO455DFR-default.jpg",
  "Lil Pump": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2325BX-default.jpg",
  "Blake": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1x7AEb-default.jpg",
  "Sheck Wes": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1EpHA7-default.jpg",
  "Pantera": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0zub2o-default.jpg",
  "Ab-Soul": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO05f4xq-default.jpg",
  "A$AP Ferg": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO34ir9m-default.jpg",
  "Dr. Dre": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3VkoW4-default.jpg",
  "Mobb Deep": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO41tfFK-default.jpg",
  "A$AP Mob": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4tBJWo-default.jpg",
  "SiR": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2fgLDY-default.jpg",
  "Cardi B": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2xmY3T-default.jpg",
  "Daft Punk": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2CNgSk-default.jpg",
  "City Morgue": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0JlbBq-default.jpg",
  "Holly Hood": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO27oWI2-default.jpg",
  "SZA": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4qHCUg-default.jpg",
  "mishlawi": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1cH1nB-default.jpg",
  "2 Chainz": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0BfCve-default.jpg",
  "Young Thug": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2WaFyg-default.jpg",
  "Joyner Lucas": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3UeKU8-default.jpg",
  "Wiz Khalifa": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0yI3tK-default.jpg",
  "Mike WiLL Made-It": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0pzAJi-default.jpg",
  "Richie Campbell": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1piJ4v-default.jpg",
  "Lil Uzi Vert": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2OQoKY-default.jpg",
  "Lil Dicky": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0OxbYQ-default.jpg",
  "LON3R JOHNY": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0GpqnP-default.jpg",
  "Flatbush Zombies": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0EUtQQ-default.jpg",
  "OG Maco": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbUSHhaB2hPB_1D8VXp3ppm9s8sHa1jqMRMQ&s",
  "Kodak Black": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2oTcyc-default.jpg",
  "Smokepurpp": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO18RIaI-default.jpg",
  "Bruno Mars": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO03DwPK-default.jpg",
  "Mick Jenkins": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0VNT8I-default.jpg",
  "D. LYNCH": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0WvkRO-default.jpg",
  "Julinho Ksd": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4ldcmk-default.jpg",
  "Token": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2sw1fh-default.jpg",
  "WESTSIDE BOOGIE": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEOmNAGncDVG4hr0AratVAldwJ4KdU0GNrXw&s",
  "Warren G": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1urM9G-default.jpg",
  "Baby Keem": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3t7Mpz-default.jpg",
  "Gorillaz": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO25rXbO-default.jpg",
  "Dave": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3Y4Tg4-default.jpg",
  "KIDS SEE GHOSTS": "https://pickasso.spotifycdn.com/image/ab67c0de0000deef/dt/v1/img/radio/artist/2hPgGN4uhvXAxiXQBIXOmE/fr",
  "Queen": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0ENBD2-default.jpg",
  "Metallica": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1sJmec-default.jpg",
  "Slipknot": "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84f3f5079aab8da1e47feadc2e",
  "9 Miller": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2FsOjO-default.jpg",
  "A Perfect Circle": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2IC32E-default.jpg",
  "ABBA": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0nVzAk-default.jpg",
  "ANDREZO": "https://pickasso.spotifycdn.com/image/ab67c0de0000deef/dt/v1/img/radio/artist/4gHzU6X4vIGR06pt7mlX60/en",
  "Aleksandir": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3BAbcv-default.jpg",
  "Ana Castela": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1vscg0-default.jpg",
  "Anitta": "https://pbs.twimg.com/media/FztzQQHWwAQYr8_.jpg",
  "Arctic Monkeys": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4BaAkp-default.jpg",
  "Ari Lennox": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0PAvyy-default.jpg",
  "Ariana Grande": "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84cf6f6e01a5d69098b836887c",
  "Bad Bunny": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2Aq9I4-default.jpg",
  "Blues Delight": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO20XFHd-default.jpg",
  "Brent Faiyaz": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO216tjq-default.jpg",
  "Bryson Tiller": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1wFOHS-default.jpg",
  "Buster Benton": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1SeeoE-default.jpg",
  "Cabaret Nocturne": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0gyPlN-default.jpg",
  "Chase Atlantic": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4gtw7S-default.jpg",
  "Chris Brown": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4fRiko-default.jpg",
  "DENNIS": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3RqpTG-default.jpg",
  "DJ Cayoo": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2s60Ux-default.jpg",
  "DaBaby": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2B3mUC-default.jpg",
  "Deftones": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3WNHaM-default.jpg",
  "Dua Lipa": "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84361d82da2060a0dc42adafbc",
  "FKJ": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1x7AE9-default.jpg",
  "FRANKIEONTHEGUITAR": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2zOu0H-default.jpg",
  "Frank Ocean": "https://i.scdn.co/image/ab67706f000000023fc91b90ebec9607f4c0b5ab",
  "Future": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO133u6s-default.jpg",
  "Gesaffelstein": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1TXcDE-default.jpg",
  "Gson": "https://pickasso.spotifycdn.com/image/ab67c0de0000deef/dt/v1/img/radio/artist/6XjHGcba7ZbaZ6nYtwhaCj/en",
  "HERE´S JOHNNY": "https://pickasso.spotifycdn.com/image/ab67c0de0000deef/dt/v1/img/radio/artist/0xRIv1ohFNq4YEjbGQoDac/en",
  "Imagine Dragons": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2YqUuI-default.jpg",
  "JPEGMAFIA": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3Sg1fp-default.jpg",
  "JT Coldfire": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1g5EQg-default.jpg",
  "Jaden": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0fREFG-default.jpg",
  "Jimmy P": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0pJLxu-default.jpg",
  "Justin Bieber": "https://pbs.twimg.com/media/DwAJLioX0AA2WCh.jpg",
  "Kadu Martins": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO30PoU9-default.jpg",
  "Kali Uchis": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO14xkre-default.jpg",
  "King Gizzard & The Lizard Wizard": "https://pickasso.spotifycdn.com/image/ab67c0de0000deef/dt/v1/img/radio/artist/6XYvaoDGE0VmRt83Jss9Sn/de",
  "Korn": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2fOjra-default.jpg",
  "Labrinth": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1hiJc4-default.jpg",
  "Leo Santana": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4AU5os-default.jpg",
  "Lexa": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO07uQHn-default.jpg",
  "Lhast": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2oElUv-default.jpg",
  "Lil Baby": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO359MM7-default.jpg",
  "Limp Bizkit": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0AuSbK-default.jpg",
  "Louis C.K.": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2uhiYp-default.jpg",
  "MC Braz": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4jbfXy-default.jpg",
  "MC Guh SR": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0IxGUg-default.jpg",
  "MC Kevin o Chris": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1GizsZ-default.jpg",
  "MC Mazzie": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZrUht7sd6pr95zOMFiZnOFIV9Hd_-n_uEdA&s",
  "MC Ryan SP": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4bQI7e-default.jpg",
  "Mc Livinho": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4m2lsk-default.jpg",
  "Mc Morena": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1dsjN7-default.jpg",
  "Mc Paiva ZS": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO05zq9Q-default.jpg",
  "Melanie Martinez": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3zuWdi-default.jpg",
  "Metro Boomin": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO06Ki7m-default.jpg",
  "Mick Gordon": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0yJqIU-default.jpg",
  "N.E.R.D": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3fO1bF-default.jpg",
  "Ne-Yo": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO197W3C-default.jpg",
  "New Order": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0gsMh2-default.jpg",
  "Offset": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2Ilh3G-default.jpg",
  "Olivia Rodrigo": "https://i.scdn.co/image/ab67706f00000002347064f35c60a7c28984226b",
  "Outkast": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0Wc5ry-default.jpg",
  "PARTYNEXTDOOR": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1yvnUc-default.jpg",
  "PEDRO SAMPAIO": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3fpOLe-default.jpg",
  "Pabllo Vittar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsI3aeo0xpUQT6u01Hkr6vzWxkJf7b4JIODg&s",
  "Phoenix Rdc": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3ondaw-default.jpg",
  "PinkPantheress": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4dKp33-default.jpg",
  "Primus": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO3zZcBq-default.jpg",
  "Queens of the Stone Age": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2zVDhu-default.jpg",
  "Rage Against The Machine": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1fXGqk-default.jpg",
  "Sara Landry": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4hwpFv-default.jpg",
  "Snoop Dogg": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4jkBCE-default.jpg",
  "Swedish House Mafia": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0H7Hk1-default.jpg",
  "Tate McRae": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2nSXaa-default.jpg",
  "The Prodigy": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2wNuKI-default.jpg",
  "Tory Lanez": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1jLCo0-default.jpg",
  "Ty Dolla $ign": "https://pickasso.spotifycdn.com/image/ab67c0de0000deef/dt/v1/img/radio/artist/7c0XG5cIJTrrAgEC3ULPiq/en",
  "Veigh": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO2V6FOw-default.jpg",
  "Waze": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO0iNY65-default.jpg",
  "Wu-Tang Clan": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO1Mfhq8-default.jpg",
  "Young M.A": "https://thisis-images.spotifycdn.com/37i9dQZF1DZ06evO4BfxcY-default.jpg"
};